steps:
  - name: "gcr.io/cloud-builders/npm"
    args: ["install"]
    dir: "functions"
  #- name: "gcr.io/cloud-builders/gcloud"
  #  args:
  #    - functions
  #    - deploy
  #    - jstp-23-backend
  #    - --source=.
  #    - --runtime
  #    - nodejs12
  #    - --trigger-http
  #  dir: "functions"
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - functions
      - deploy
      - world-data-watch
      - --source=worldWatch.js
      - --runtime
      - nodejs12
      - --trigger-http
    dir: "functions"
