steps:
  - name: "gcr.io/cloud-builders/npm"
    args: ["install"]
    dir: "functions"
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - functions
      - deploy
      - jstp-23-backend
      - --source=.
      - --runtime
      - node12
      - --trigger-http
    dir: "functions"
